text ="hello \"vikings world\" world"
age = 30
print(text[2:5])
print(text[:5])
print(text[2:])
print(text[-5:-2])
print(text[-5:])
print(text[-5:])
print(text[:])
print(text.upper())
print(text.lower())
print(text.capitalize())
print(text.title())
print(f" I am {age} years old")
print(6 & 3)